name: Selenium CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up JDK
      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'

      # Step 3: Cache Maven dependencies
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Install Google Chrome
      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      # Step 5: Verify Chrome installation
      - name: Verify Google Chrome installation
        run: |
          google-chrome --version || echo "Google Chrome is not installed"

      # Step 6: Detect Chrome version
      - name: Detect Chrome version
        run: |
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | awk -F. '{print $1}')
          echo "Detected Chrome version: $CHROME_VERSION"

      # Step 7: Validate ChromeDriver URL
      - name: Validate ChromeDriver URL
        run: |
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | awk -F. '{print $1}')
          CHROMEDRIVER_VERSION=$(curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION})
          echo "ChromeDriver version: $CHROMEDRIVER_VERSION"
          echo "Download URL: https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"

      # Step 8: Install ChromeDriver
      - name: Install ChromeDriver
        run: |
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | awk -F. '{print $1}')
          CHROMEDRIVER_VERSION=$(curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION})
          wget -q https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          chmod +x /usr/local/bin/chromedriver

      # Step 9: Set up Xvfb virtual display
      - name: Set up Xvfb virtual display
        run: |
          sudo apt-get install -y xvfb
          export DISPLAY=:99
          Xvfb :99 -screen 0 1024x768x24 &

      # Step 10: Install dependencies
      - name: Install dependencies
        run: mvn clean install

      # Step 11: Run Selenium tests
      - name: Run Selenium tests
        run: mvn test